server:
  port: 8000
  development: true

spring:
  application:
    name: imagesBase
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/images_base?serverTimezone=Asia%2fShanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456789

images-base-properties:
  swagger:
    enable: true
    title: "图床项目API"
    description: "图床项目SwaggerAPI管理"
    version: "1.0"
    group-name: "ImageBase"
    base-package: com.images_base.backend.controller
  jwt:
    id: images_base
    secret: C60B718C6F6D50A578B0043B4EF43028
    token-expired-time: 72
    time-unit: HOURS
    url-patterns:
      - "/**"
    exclude-url-patterns:
      - "/swagger-ui/**"
      - "/swagger-resources/**"
      - "/v3/api-docs"
      - "/**/call_back/**"
      - "/login"

mybatis-plus:
  mapper-locations:
    - classpath:/mappers/*.xml
  configuration:
    # 支持Entity中字段定义为Java Enum枚举类型
    default-enum-type-handler:
      org.apache.ibatis.type.EnumOrdinalTypeHandler
    # 解决查询返回结果含null没有对应字段值问题
    map-underscore-to-camel-case: true
    # 存储字段策略 0:忽略判断; 1:非null判断; 2:非null非空值判断
    field-strategy: 0
    global-config:
      db-config:
        logic-delete-value: 1
        logic-not-delete-value: 0
